################################################################################
# FUNDING.yml for Ultrahand-Overlay Repository
# Author: ppkantorski
# Description:
#   This FUNDING.yml file is used to configure the sponsor button for the Ultrahand-Overlay
#   repository on GitHub. It specifies the supported funding model platforms and their
#   respective account information.
#
#   For more details on how to configure the sponsor button, please refer to the
#   GitHub documentation: https://docs.github.com/en/account-and-profile/managing-subscriptions-and-supporting-developers/configuring-funding-support-in-your-repository
#
#   GitHub Repository: https://github.com/ppkantorski/Ultrahand-Overlay
#
################################################################################

github: ppkantorski
ko_fi: b0rd2dEAth
